### ISSUE TITLE
Issue Installing Discord-Components

### ISSUE THREAD

**Issue by Progaming19199** [astrxnomo/discord-ticket-bot-py#2]
I get the this error whenever I try and install Discord-Components

![image](https://user-images.githubusercontent.com/71011207/209484661-47d8686e-bbc1-48da-9181-49dc55cd1ece.png)

**Comment by Onurada** [comment]
I get too

**Comment by chillymosh** [comment]
Why are you even using discord-components? Dpy 2 has all of them built in already.
Second, do not use sqlite3 use aiosqlite or asqlite as they are async and non-blocking.

**Comment by jojoexperte7289** [comment]
I have forked this repo and I want to make this code work again. The owner doesn't seem to be active on GitHub anymore.

**Comment by SPFck** [comment]
Just use this req.txt file https://github.com/pramaurya/discord-ticket-bot-py/blob/main/req.txt
